### ISSUE TITLE
Locale for Facebook plugins must be in the following format : ll_CC

### ISSUE THREAD

**Issue by sensorario** [digitick/yii-faceplugs#1]
This is my config file:

```
return array(
    'language' => 'it',
```

If I set it to 

```
return array(
    'language' => 'it_IT',
```

yii-faceplugs work fine. If not ... I get this error: "Locale for Facebook plugins must be in the following format : ll_CC". Maybe is wrog set language
This is my config file:

```
return array(
    'language' => 'it',
```

but, there is a way to go right even if language is only 'it'?

**Comment by ianare** [comment]
According to the FB documentation the language must be in that format.
